function trials = confirm_tiling_succeeded

monitorInformation;   % not strictly needed here, verify function calls it itself
table = {'Sector Azimuth (deg)', -120, 10, 110;...
    'Sector Eccentricity (deg)', 0, 10, 70;...
    'Sector Luminance (binary)', 0, 1, 1;...
    'Timing (delay,duration,wait)', 0, 0.095, 0;...
    'Blank', 0, [], [];...
    'Randomize', 1, [], [];...
    'Interleave', 0, [], [];...
    'Repeats', 2, [], [];...
    'Initialization Screen (s)', 5, [], []};
stimType = 'Receptive Field Mapping';

trials = trialStruct_RFmapFast(stimType, table);
final_struct = verify_RFmap_polar_tiling(trials);