%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ReceptiveFieldMapping_FloorBubble_Static
%
% Fan-shaped receptive field mapping stimulus.
%
% The stimulus consists of 10-degree trapezoidal sectors extending from
% an inner gap around the mouse's projected head position to the edge of
% the monitor.
%
% The trial structure is generated by:
%
%     trialStruct_RFmapFan
%
% and this function is responsible for converting each angular sector
% into the appropriate monitor coordinates and presenting it using
% Psychtoolbox.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function ReceptiveFieldMapping_FloorBubble_Static(trials)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MONITOR INFORMATION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

monitorInformation;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TURN OFF PTB SYSTEM CHECK REPORT
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Screen('Preference', 'Verbosity', 1);

Screen('Preference', 'VisualDebuglevel', 3);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OPEN SCREEN
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

try

    AssertOpenGL;


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % MONITOR PARAMETERS
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    screenNumber = monitorInfo.screenNumber;

    screenWidth_cm  = monitorInfo.screenSizecmX;
    screenHeight_cm = monitorInfo.screenSizecmY;

    screenWidth_pix  = monitorInfo.screenSizePixX;
    screenHeight_pix = monitorInfo.screenSizePixY;


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % COLOR INFORMATION
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    whitePix = WhiteIndex(screenNumber);
    blackPix = BlackIndex(screenNumber);

    whiteLum = PixToLum(whitePix);
    blackLum = PixToLum(blackPix);

    grayLum = (whiteLum + blackLum)/2;

    grayPix = GammaCorrect(grayLum);


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % MOUSE GEOMETRY
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    mouseDistance_cm = monitorInfo.screenDistcm;


    % Mouse projection:
    %
    % 24.5 cm from RIGHT edge
    %

    mouseX_cm = screenWidth_cm - 24.5;


    % 14 cm from BOTTOM

    mouseY_cm = 14.0;


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % CM -> PIXEL CONVERSION
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    pixPerCmX = screenWidth_pix / screenWidth_cm;
    pixPerCmY = screenHeight_pix / screenHeight_cm;


    % Mouse projection in pixels

    mouseX_pix = mouseX_cm * pixPerCmX;

    mouseY_pix = ...
        screenHeight_pix - ...
        mouseY_cm * pixPerCmY;


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % HIDE CURSOR
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    HideCursor;


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % OPEN WINDOW
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    [w, screenRect] = Screen( ...
        'OpenWindow', ...
        screenNumber, ...
        grayPix);


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % PRIORITY
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    priorityLevel = MaxPriority(w);

    Priority(priorityLevel);


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % INTERFRAME INTERVAL
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    ifi = Screen('GetFlipInterval', w);

    waitframes = 1;

    ifiDuration = waitframes * ifi;


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % INITIAL SCREEN
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    Screen('FillRect', w, grayPix);


    % Draw mouse projection for testing/initialization

    Screen('FillOval', w, [0 255 0], ...
        [ ...
        mouseX_pix-6, ...
        mouseY_pix-6, ...
        mouseX_pix+6, ...
        mouseY_pix+6 ...
        ]);


    Screen('Flip', w);


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % INITIALIZATION PERIOD
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    stimInitScreen( ...
        w, ...
        trials(1).Initialization_Screen, ...
        grayPix, ...
        ifiDuration);


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % PRECOMPUTE TRAPEZOIDS
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    nTrials = numel(trials);

    trapezoids = cell(nTrials,1);


    for trial = 1:nTrials

        %---------------------------------------------------------------
        % Blank trial
        %---------------------------------------------------------------

        if strcmp(trials(trial).Stimulus_Type, 'Blank')

            trapezoids{trial} = [];

            continue;

        end


        %---------------------------------------------------------------
        % Get angular parameters
        %---------------------------------------------------------------

        theta1 = trials(trial).Sector_Angle;

        theta2 = theta1 + ...
            trials(trial).Sector_Width;


        %---------------------------------------------------------------
        % Inner gap
        %---------------------------------------------------------------

        innerRadius_cm = ...
            trials(trial).Inner_Gap;


        %---------------------------------------------------------------
        % INNER CORNER 1
        %---------------------------------------------------------------

        x1_inner = ...
            mouseX_cm + ...
            innerRadius_cm * cosd(theta1);

        y1_inner = ...
            mouseY_cm + ...
            innerRadius_cm * sind(theta1);


        %---------------------------------------------------------------
        % INNER CORNER 2
        %---------------------------------------------------------------

        x2_inner = ...
            mouseX_cm + ...
            innerRadius_cm * cosd(theta2);

        y2_inner = ...
            mouseY_cm + ...
            innerRadius_cm * sind(theta2);


        %---------------------------------------------------------------
        % OUTER CORNER 1
        %---------------------------------------------------------------

        [x1_outer, y1_outer] = ...
            rayScreenIntersection( ...
            mouseX_cm, ...
            mouseY_cm, ...
            theta1, ...
            screenWidth_cm, ...
            screenHeight_cm);


        %---------------------------------------------------------------
        % OUTER CORNER 2
        %---------------------------------------------------------------

        [x2_outer, y2_outer] = ...
            rayScreenIntersection( ...
            mouseX_cm, ...
            mouseY_cm, ...
            theta2, ...
            screenWidth_cm, ...
            screenHeight_cm);


        %---------------------------------------------------------------
        % Convert cm -> pixels
        %---------------------------------------------------------------

        xPix = [ ...
            x1_inner ...
            x2_inner ...
            x2_outer ...
            x1_outer ...
            ] * pixPerCmX;


        yPix = screenHeight_pix - ...
            [ ...
            y1_inner ...
            y2_inner ...
            y2_outer ...
            y1_outer ...
            ] * pixPerCmY;


        %---------------------------------------------------------------
        % Store polygon
        %---------------------------------------------------------------

        trapezoids{trial} = ...
            [xPix(:), yPix(:)];

    end


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % MAIN TRIAL LOOP
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    exitLoop = 0;


    for trial = 1:nTrials

        if exitLoop == 1

            break;

        end


        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GET TIMING
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        delay = trials(trial).Timing(1);

        duration = trials(trial).Timing(2);

        wait = trials(trial).Timing(3);


        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % DETERMINE STIMULUS LUMINANCE
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        if trials(trial).Square_Luminance == 0

            stimLum = blackPix;

        elseif trials(trial).Square_Luminance == 1

            stimLum = whitePix;

        end


        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % BLANK TRIAL
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        if strcmp(trials(trial).Stimulus_Type, 'Blank')

            vbl = Screen('Flip', w);

            waitTime = vbl + duration;


            while vbl < waitTime

                Screen('FillRect', w, grayPix);

                vbl = Screen( ...
                    'Flip', ...
                    w, ...
                    vbl + (waitframes - 0.5) * ifi);


                if KbCheck

                    exitLoop = 1;

                    break;

                end

            end

            continue;

        end


        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % DELAY PERIOD
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        vbl = Screen('Flip', w);

        delayTime = vbl + delay;


        while vbl < delayTime

            Screen('FillRect', w, grayPix);

            vbl = Screen( ...
                'Flip', ...
                w, ...
                vbl + (waitframes - 0.5) * ifi);


            if KbCheck

                exitLoop = 1;

                break;

            end

        end


        if exitLoop == 1

            break;

        end


        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % STIMULUS PERIOD
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        runtime = vbl + duration;


        while vbl < runtime

            %-------------------------------------------------------------
            % Gray background
            %-------------------------------------------------------------

            Screen('FillRect', w, grayPix);


            %-------------------------------------------------------------
            % Draw trapezoid
            %-------------------------------------------------------------

            Screen( ...
                'FillPoly', ...
                w, ...
                stimLum, ...
                trapezoids{trial});


            %-------------------------------------------------------------
            % Flip
            %-------------------------------------------------------------

            vbl = Screen( ...
                'Flip', ...
                w, ...
                vbl + (waitframes - 0.5) * ifi);


            %-------------------------------------------------------------
            % Keyboard check
            %-------------------------------------------------------------

            if KbCheck

                exitLoop = 1;

                break;

            end

        end


        if exitLoop == 1

            break;

        end


        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % INTER-STIMULUS WAIT
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        waitTime = vbl + wait;


        while vbl < waitTime

            Screen('FillRect', w, grayPix);

            vbl = Screen( ...
                'Flip', ...
                w, ...
                vbl + (waitframes - 0.5) * ifi);


            if KbCheck

                exitLoop = 1;

                break;

            end

        end

    end


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % FINAL GRAY SCREEN
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    vbl = Screen('Flip', w);

    waitTime = vbl + 2;


    while vbl < waitTime

        Screen('FillRect', w, grayPix);

        vbl = Screen( ...
            'Flip', ...
            w, ...
            vbl + (waitframes - 0.5) * ifi);

    end


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % RESTORE PRIORITY
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    Priority(0);


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % CLOSE SCREEN
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    Screen('CloseAll');

    ShowCursor;


catch

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % ERROR CLEANUP
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    Screen('CloseAll');

    Priority(0);

    ShowCursor;

    psychrethrow(psychlasterror);

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RESTORE PTB VERBOSITY
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Screen('Preference', 'Verbosity', 3);


end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RAY / SCREEN INTERSECTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [xHit, yHit] = ...
    rayScreenIntersection( ...
    x0, y0, theta, ...
    screenWidth, screenHeight)


% Coordinate convention:
%
% 0 degrees   = directly RIGHT
% positive    = DOWN / clockwise
% negative    = UP / counterclockwise
%
% This matches the fan orientation we already tested.


dx = cosd(theta);

dy = sind(theta);


candidates = [];


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RIGHT EDGE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if dx > 0

    t = (screenWidth - x0) / dx;

    y = y0 + t * dy;


    if y >= 0 && y <= screenHeight

        candidates(end+1,:) = ...
            [t, screenWidth, y];

    end

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% LEFT EDGE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if dx < 0

    t = (0 - x0) / dx;

    y = y0 + t * dy;


    if y >= 0 && y <= screenHeight

        candidates(end+1,:) = ...
            [t, 0, y];

    end

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TOP EDGE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if dy < 0

    t = (0 - y0) / dy;

    x = x0 + t * dx;


    if x >= 0 && x <= screenWidth

        candidates(end+1,:) = ...
            [t, x, 0];

    end

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% BOTTOM EDGE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if dy > 0

    t = (screenHeight - y0) / dy;

    x = x0 + t * dx;


    if x >= 0 && x <= screenWidth

        candidates(end+1,:) = ...
            [t, x, screenHeight];

    end

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SELECT CLOSEST INTERSECTION
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if isempty(candidates)

    error( ...
        'Ray at %.1f degrees does not intersect monitor.', ...
        theta);

end


[~, idx] = min(candidates(:,1));

xHit = candidates(idx,2);

yHit = candidates(idx,3);


end
